### ISSUE TITLE
review Hewlett OPN RFP

### ISSUE THREAD

**Issue by tvol** [creativecommons/open-policy-network#2]
https://docs.google.com/a/creativecommons.org/document/d/1PcCgZe4szfbO4lVik9jsdr37xamOxYG9_3aVCPz5noo/edit#

**Comment by sarahpearson** [comment]
Reviewed and added comments. I will ping Diane to see if she has any additional edits. 

Do you know where I can find the original agreement with Hewlett? I'll want to look at that before I draft the subcontractor agreement, which I will do now.

**Comment by tvol** [comment]
@sarahpearson will send you a link

**Comment by tvol** [comment]
@sarahpearson thanks for the edits to the document. @peterspdx if possible please add anything you have by COB today. we'd like to launch this tomorrow. thanks!

**Comment by tvol** [comment]
thanks @peterspdx @sarahpearson
