### ISSUE TITLE
start google doc for OPN MozFest proposal

### ISSUE THREAD

**Issue by tvol** [creativecommons/open-policy-network#25]

**Comment by tvol** [comment]
https://docs.google.com/document/d/1rNfSCZTEKk9ZAqd1S7k8awDy5uO0B7ozqRcXH2MHoDw/edit

**Comment by tvol** [comment]
need to submit by 31 August

**Comment by cablegreen** [comment]
Tim - looks really good - I have no comments / changes to offer.

**Comment by tvol** [comment]
submitted
