### ISSUE TITLE
requesting your review of RFP with deadline 10/27

### ISSUE THREAD

**Issue by rebeccakross** [creativecommons/open-policy-network#34]
@tvol @cablegreen will you review and we can discuss? I'm thinking about a few possibilities related to OPN, OER, or other affiliate related work in developing countries you may be working on or aware of could be a fit: http://www.international.gc.ca/development-developpement/partners-partenaires/calls-appels/techno-platforms-plateformes-techno.aspx?lang=eng

@Scott-CC can you confirm eligibility of minimum 50K cash match from Canadian sources (if we went in for $1M ask over 3-5 years)?

**Comment by tvol** [comment]
@rebeccalendl @Scott-CC  do you know if CC is definitely eligible to submit an application?

**Comment by cablegreen** [comment]
happy to talk about it ... timeline would be very tight with the Summit right around the corner
