### ISSUE TITLE
interim grant report due 12/1/15

### ISSUE THREAD

**Issue by tvol** [creativecommons/open-policy-network#36]

**Comment by tvol** [comment]
hi @mattl @robmyers We need to finish up our interim grant report to Hewlett by tomorrow. Can you add a paragraph of text regarding progress on the list and search to this document? https://docs.google.com/document/d/18R0Hvn7XOvG3k-Pi78O_5Cn8eS7coaN6mKAF-ONaVKY/edit cc @cablegreen @ryanmerkley

**Comment by tvol** [comment]
@robmyers thanks for adding the text. @mattl if you need to review it, please do so ASAP. this report needs to go out today. cc @cablegreen

**Comment by mattl** [comment]
i had a look. seems good to me.

**Comment by tvol** [comment]
@mattl ok thanks
