### ISSUE TITLE
blocked from publishing blog post on openpolicynetwork.org

### ISSUE THREAD

**Issue by tvol** [creativecommons/open-policy-network#47]
<img width="671" alt="screen shot 2016-03-28 at 9 33 30 am" src="https://cloud.githubusercontent.com/assets/231665/14083009/34a498d0-f4c8-11e5-8912-afd0b0ffd631.png">

**Comment by mattl** [comment]
Can you try now?

**Comment by tvol** [comment]
no. it might have something to do with the "schedule" feature. i just opened a new blog post and published it without that.

**Comment by mattl** [comment]
OPN was under attack for a while, so we upped the security on it, which is
what was telling you to go away.

Are you on your usual internet connection?

**Comment by tvol** [comment]
yes

**Comment by mattl** [comment]
Can you try an incognito/private window?

**Comment by tvol** [comment]
i'm still being blocked when attempting to save a draft post, even in incognito mode

**Comment by tvol** [comment]
@mattl any idea what's going on with the blocking on this?
